version: '3.8'
services:
  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5434:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:5.1
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5435:80
volumes:
  postgres_volume:
